---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayfly-go
  namespace: environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayfly-go
  template:
    metadata:
      labels:
        app: mayfly-go
    spec:
      containers:
      - name: mayfly-go
        image: registry.cn-hangzhou.aliyuncs.com/magictommy/mayfly-go-redis-web:v1.7.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18888
        resources:
          limits:
            memory: "2000Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "100m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
---
apiVersion: v1
kind: Service
metadata:
  name: mayfly-go
  namespace: environment
spec:
  selector:
    app: mayfly-go
  ports:
    - protocol: TCP
      port: 18888
      targetPort: 18888
      nodePort: 32763
  type: NodePort