version: '3.1'
services:
  kubespray-nginx:
    container_name: kubespray-nginx
    image: docker.io/library/nginx:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/data/
    ports:
      - 38088:80