kernel_version: '5.4.260'
runc_version: '1.1.12'
docker_version: '25.0.3'
cni_plugins_version: 'v1.4.0'
containerd_version: '1.7.13'
nerdctl_full_version: '1.7.4'
crictl_version: 'v1.29.0'
cri_dockerd_version: '0.3.10'
etcd_version: 'v3.5.12'
cfssl_version: '1.6.4'
helm_version: '3.14.1'
kubernetes_server_version: '1.29.2'
kubernetes_client_version: '1.29.2'
nginx_version: '1.25.3'
cri_o_version: 'V1.29.1'
docker_compose_version: 'v2.24.6'
harbor_version: 'v2.9.2'
calicoctl_version: 3.27.2
cilium_version: v0.15.23
hubble_version: v0.13.0
velero_version: v1.13.0
skopeo_version: v1.14.2
yq_version: v4.41.1