- name: 配置etcdctl
  template:
    src: etcdctl.yml.j2
    dest: /etc/profile.d/etcdctl.sh

- name: 查看etcd状态
  shell: systemctl status etcd.service
  register: etcd_status

- name: 打印etcd服务状态
  debug:
    var: etcd_status.stdout_lines

- name: 查看集群状态
  shell: "{{ bin_dir }}/etcdctl \
        --cacert={{ cluster_dir }}/etcd/ssl/etcd-ca.pem \
        --cert={{ cluster_dir }}/etcd/ssl/etcd-server.pem \
        --key={{ cluster_dir }}/etcd/ssl/etcd-server-key.pem \
        --endpoints=https://127.0.0.1:2379  member list --write-out=table"
  register: etcd_cluster_status

- name: 打印etcd集群状态
  debug:
    var: etcd_cluster_status.stdout_lines