- name: 创建etcd证书目录
  include_tasks: create-cret.yml



- name: 分发etcd证书到各个主机
  include_tasks: distribute-cert.yml

- name: 创建etcd配置文件存放目录
  file:
    path: "{{ cluster_dir }}/etcd/conf/"
    state: directory
    mode: 0700

- name: 渲染etcd配置文件
  template:
    src: config.yml.j2
    dest: "{{ cluster_dir }}/etcd/conf/config.yml"

- name: 创建etcd的systemd unit文件
  template: 
    src: etcd-service.j2 
    dest: /etc/systemd/system/etcd.service
  tags: upgrade_etcd, restart_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd, restart_etcd, force_change_certs

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl is-active etcd.service"
  register: etcd_status
  until: '"active" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd, restart_etcd, force_change_certs

- name: 查看etcd服务状态
  include_tasks: etcd_status.yml

- name: 备份etcd
  include_tasks: backup-etcd.yml