- name: 安装基础软件包
  yum: 
    name: 
    - jq                              # 轻量JSON处理程序
    - git
    - htop
    - curl                            # 基础工具
    - wget
    - audit
    - iotop
    - ipset                           # ipvs 模式需要
    - socat                           # 用于port forwarding
    - sysstat
    - ipvsadm                         # ipvs 模式需要
    - nmap-ncat                       # 使用lb时进行端口判断时会用到
    - nfs-utils                       # 挂载nfs 共享文件需要 (创建基于 nfs的 PV 需要)
    - iscsi-initiator-utils           # iSCSI 服务端及管理命令 (管理 IP SAN。有 externel volume provisioner 时依赖)
    - net-tools
    - libseccomp
    - conntrack-tools                 # ipvs 模式需要
    - bash-completion                 # bash命令补全工具，需要重新登录服务器生效
    state: latest
  ignore_errors: true