- name: 安装 ubuntu 基础软件
  apt: 
    name:
    - jq                          # 轻量JSON处理程序，安装docker查询镜像需要
    - git
    - htop
    - curl                        # 基础工具
    - socat                       # 用于port forwarding
    - ipset                       # ipvs 模式需要
    - iotop
    - sysstat
    - ipvsadm                     # ipvs 模式需要
    - iptables
    - conntrack                   # network connection cleanup 用到
    - net-tools
    - nfs-common                  # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
    - nfs-kernel-server
    - libseccomp2                 # 安装containerd需要
    - netcat-openbsd              # 使用lb时进行端口判断时会用到
    - ca-certificates             # docker会用到
    - bash-completion             # bash命令补全工具，需要重新登录服务器生效
    - apt-transport-https         # 添加https协议的apt源会用到
    - software-properties-common  # docker会用到
    state: present
    update_cache: yes
    allow_unauthenticated: true
  ignore_errors: true