- name: 环境准备
  hosts: k8s_cluster
  tasks:
    - name: yum在线安装
      script: {{destination_dir}}/k8s_install/1.yum_install_online.sh
      when: yum_online_install == true
    
    - name: yum离线安装
      script: {{destination_dir}}/k8s_install/2.yum_install_offline.sh
      when: yum_online_install == false

    - name: 设置内核参数
      script: {{destination_dir}}/k8s_install/2.init.sh
    
    - name: 设置主机名
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: 安装containerd
      script: {{destination_dir}}/k8s_install/3.docker_install.sh
    
    - name: 校验nerdctl是否安装成功
      command: nerdctl ps
      register: nerdctl_ps

    - name: 加载离线镜像
      script: {{destination_dir}}/k8s_install/5.load_image.sh
      when: nerdctl_ps.rc == 0