- name: 环境准备
  hosts: k8s_cluster
  tasks:
    - name: yum在线安装
      shell: "/bin/bash {{ destination_dir }}/k8s_install/1.yum_install_online.sh"
      when: yum_online_install == true
      register: yum_output

    - name: Print script output
      debug:
        var: yum_output.stdout_lines

    - name: yum离线安装
      shell: "/bin/bash {{ destination_dir }}/k8s_install/2.yum_install_offline.sh"
      when: yum_online_install == false
      register: yum_offline_output
    
    - name: Print script output
      debug:
        var: yum_offline_output.stdout_lines

    - name: 设置内核参数
      shell: "/bin/bash {{ destination_dir }}/k8s_install/2.init.sh"
      register: init_output

    - name: Print script output
      debug:
        var: init_output.stdout_lines
    
    - name: 设置主机名
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: 安装containerd
      shell: "/bin/bash {{ destination_dir }}/k8s_install/3.docker_install.sh"
      register: containerd_output


    - name: Print script output
      debug:
        var: containerd_output.stdout_lines
    
    - name: 校验nerdctl是否安装成功
      command: nerdctl ps
      register: nerdctl_ps

    - name: 加载离线镜像
      shell: "/bin/bash {{ destination_dir }}/k8s_install/5.load_image.sh"
      when: nerdctl_ps.rc == 0
      register: load_image_output

    - name: Print script output
      debug:
        var: load_image_output.stdout_lines