- name: 其他master节点加入集群
  hosts: "{{ groups['kube_control_plane'][1:] }}"
  tasks:
    - name: 其他master节点加入集群
      shell: "/bin/bash {{destination_dir}}/k8s_install/7.join_master.sh"
      register: join_master
    
    - name: 打印join_master结果
      debug:
        var: join_master.stdout_lines