apiVersion: v1
kind: Service
metadata:
  name: redis-single-svc
  namespace: environment
  labels:
    app: redis-single-svc
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - nodePort: 32379
      port: 6379
      protocol: TCP
      targetPort: 6379
      name: redis
    - nodePort: 32380
      port: 9121
      protocol: TCP
      targetPort: 9121
      name: metrics
  selector:
    app: redis-signle
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-signle
  namespace: environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-signle
  template:
    metadata:
      labels:
        app: redis-signle
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      nodeSelector:
        kubernetes.io/hostname: master1
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists" 
        effect: "NoSchedule"
      priorityClassName: system-node-critical
      containers:
        - name: redis-signle
          image: docker.io/library/redis:latest
          imagePullPolicy: IfNotPresent
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-signle-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - mountPath: /etc/localtime
              name: volume-localtime
        - name: redis-exporter
          image: docker.io/oliver006/redis_exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_PASSWORD
              value: XtgsO0pPnzfNRQCC
            - name: TZ
              value: Asia/Shanghai
          securityContext:
            runAsUser: 59000
            runAsGroup: 59000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 9121
      volumes:
        - name: volume-localtime
          hostPath:
            path: /etc/localtime
        - name: redis-signle-config
          configMap:
            name: redis-signle-configmap
            items:
              - key: redis.conf
                path: redis.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-signle-configmap
  namespace: environment
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass X(tgsO0pPnzfNRQCC
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    maxclients 1000
    timeout 300
    databases 16
    appendonly no
    save ""
    #maxmemory 5000mb
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-signle-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis-signle
